# Configuración del libro
# Obtén más información en https://jupyterbook.org/customize/config.html

title: Lecciones de EMERGE
author: GeoDI Lab
copyright: "2025"
logo: EMERGE_Landsat.png

# No volver a ejecutar los cuadernos durante cada compilación
# Consulta https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Definir el nombre del archivo de salida de LaTeX para las compilaciones en PDF
latex:
  latex_documents:
    targetname: book.tex

# Agregar un archivo BibTeX para crear citas
bibtex_bibfiles:
  - references.bib

# Información sobre la ubicación del libro en la web
repository:
  url: https://github.com/geo-di-lab/emerge-lessons
  branch: main

launch_buttons:
  # thebe: true
  # binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

# Agregar botones de GitHub al libro
# Consulta https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "GeoDI_Logo.png"
  use_issues_button: true
  use_repository_button: true
